AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        ALPHA_VANTAGE_API_KEY: ""

Resources:
  # SNS Topic to send stock alerts
  StockAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: StockAlerts

  # Lambda Function to store User Prefernce ,threshold and stock symbol
  UserStockThresholdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UserStockThresholdFunction
      Handler: storeUserStockPreference.lambdaHandler
      Runtime: nodejs20.x
      CodeUri: src/
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonAPIGatewayInvokeFullAccess
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref StockAlertsTopic
      Events:
        StoreStockApi:
          Type: Api
          Properties:
            Path: /set-stock-threshold
            Method: Post

  # Lambda function to get stock price
  StockPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StockPriceFunction
      Handler: StockPriceFunction.lambdaHandler
      Runtime: nodejs20.x
      CodeUri: src/
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonSNSFullAccess
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref StockAlertsTopic
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)

  # DynamoDB Table to store user stock thresholds
  UserStockThresholdsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserStockThresholds
      AttributeDefinitions:
        - AttributeName: Username
          AttributeType: S
        - AttributeName: StockSymbol
          AttributeType: S
      KeySchema:
        - AttributeName: Username
          KeyType: HASH
        - AttributeName: StockSymbol
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
