AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        ALPHA_VANTAGE_API_KEY: ""

Resources:
  StockPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StockPriceFunction
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      CodeUri: hello-world/
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAPIGatewayInvokeFullAccess
      Events:
        StockPriceApi:
          Type: Api
          Properties:
            Path: /stockprice
            Method: get

  # DynamoDB Table to store user stock thresholds
  UserStockThresholdsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserStockThresholds
      AttributeDefinitions:
        - AttributeName: Username
          AttributeType: S
        - AttributeName: StockSymbol
          AttributeType: S
      KeySchema:
        - AttributeName: Username
          KeyType: HASH
        - AttributeName: StockSymbol
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
